global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/62e5b561-f020-45cb-9d27-d1abeae67be9'
          send_resolved: false